const BANK = [
{id:1, topic:"assertive", direct:`She said, “I like tea.”`, indirect:`She said that she liked tea.`},
{id:2, topic:"assertive", direct:`He said, “I am writing a letter.”`, indirect:`He said that he was writing a letter.`},
{id:3, topic:"assertive", direct:`They said, “We have won the match.”`, indirect:`They said that they had won the match.`},
{id:4, topic:"timeplace", direct:`Ramesh said, “I bought a new book yesterday.”`, indirect:`Ramesh said that he had bought a new book the previous day.`},
{id:5, topic:"assertive", direct:`The old man said, “I was feeling weak.”`, indirect:`The old man said that he had been feeling weak.`},
{id:6, topic:"modals", direct:`The doctor said, “You must take this medicine.”`, indirect:`The doctor said that I must take that medicine.`},
{id:7, topic:"assertive", direct:`Mina said to me, “I have completed the work.”`, indirect:`Mina told me that she had completed the work.`},
{id:8, topic:"timeplace", direct:`The boys said, “We are playing in the field now.”`, indirect:`The boys said that they were playing in the field then.`},
{id:9, topic:"modals", direct:`Father said, “I will return tomorrow.”`, indirect:`Father said that he would return the next day.`},
{id:10, topic:"assertive", direct:`The teacher said, “Honesty is the best policy.”`, indirect:`The teacher said that honesty is the best policy.`},
{id:11, topic:"assertive", direct:`She said, “I have been reading for two hours.”`, indirect:`She said that she had been reading for two hours.`},
{id:12, topic:"modals", direct:`He said, “I cannot attend the meeting.”`, indirect:`He said that he could not attend the meeting.`},
{id:13, topic:"assertive", direct:`Rahul said to his friend, “I have lost my pen.”`, indirect:`Rahul told his friend that he had lost his pen.`},
{id:14, topic:"assertive", direct:`The guard said, “The gate closes at 9 p.m.”`, indirect:`The guard said that the gate closed at 9 p.m.`},
{id:15, topic:"assertive", direct:`The child said, “I was sleeping.”`, indirect:`The child said that he/she had been sleeping.`},
{id:16, topic:"assertive", direct:`The woman said, “I have never seen such a place.”`, indirect:`The woman said that she had never seen such a place.`},
{id:17, topic:"modals", direct:`He said, “We will start next week.”`, indirect:`He said that they would start the following week.`},
{id:18, topic:"assertive", direct:`The shopkeeper said, “These mangoes are fresh.”`, indirect:`The shopkeeper said that those mangoes were fresh.`},
{id:19, topic:"modals", direct:`She said, “I may go there.”`, indirect:`She said that she might go there.`},
{id:20, topic:"assertive", direct:`The farmer said, “It rained heavily last night.”`, indirect:`The farmer said that it had rained heavily the previous night.`},
{id:21, topic:"assertive", direct:`The students said, “We are preparing for the test.”`, indirect:`The students said that they were preparing for the test.`},
{id:22, topic:"assertive", direct:`She said to her mother, “I have done my duty.”`, indirect:`She told her mother that she had done her duty.`},
{id:23, topic:"assertive", direct:`He said, “I had a headache.”`, indirect:`He said that he had had a headache.`},
{id:24, topic:"assertive", direct:`The coach said, “Practice makes a player perfect.”`, indirect:`The coach said that practice makes a player perfect.`},
{id:25, topic:"modals", direct:`He said, “I shall help you.”`, indirect:`He said that he would help me.`},
{id:26, topic:"interrogative", direct:`He said to me, “Are you coming today?”`, indirect:`He asked me if I was coming that day.`},
{id:27, topic:"interrogative", direct:`She said, “Do you know the answer?”`, indirect:`She asked if I knew the answer.`},
{id:28, topic:"interrogative", direct:`They said to him, “Have you seen this film?”`, indirect:`They asked him whether he had seen that film.`},
{id:29, topic:"interrogative", direct:`The teacher said to the student, “Did you complete the lesson?”`, indirect:`The teacher asked the student if he/she had completed the lesson.`},
{id:30, topic:"modals", direct:`Mother said to me, “Will you help me?”`, indirect:`Mother asked me if I would help her.`},
{id:31, topic:"modals", direct:`He said, “Can you swim?”`, indirect:`He asked if I could swim.`},
{id:32, topic:"modals", direct:`She said, “May I come in?”`, indirect:`She asked if she might come in.`},
{id:33, topic:"interrogative", direct:`The man said to the boy, “Is your father at home?”`, indirect:`The man asked the boy if his father was at home.`},
{id:34, topic:"interrogative", direct:`The doctor said to her, “Do you smoke?”`, indirect:`The doctor asked her if she smoked.`},
{id:35, topic:"interrogative", direct:`The officer said, “Have the workers arrived?”`, indirect:`The officer asked if the workers had arrived.`},
{id:36, topic:"imperative", direct:`He said to me, “Where are you going?”`, indirect:`He asked me where I was going.`},
{id:37, topic:"optative", direct:`She said, “What are you doing now?”`, indirect:`She asked what I was doing then.`},
{id:38, topic:"interrogative", direct:`Father said, “Why were you late yesterday?”`, indirect:`Father asked why I had been late the previous day.`},
{id:39, topic:"interrogative", direct:`The teacher said, “How did you solve the problem?”`, indirect:`The teacher asked how I had solved the problem.`},
{id:40, topic:"modals", direct:`She said to him, “When will you meet me?”`, indirect:`She asked him when he would meet her.`},
{id:41, topic:"interrogative", direct:`The boy said, “Who is calling me?”`, indirect:`The boy asked who was calling him.`},
{id:42, topic:"interrogative", direct:`He said, “Which book do you want?”`, indirect:`He asked which book I wanted.`},
{id:43, topic:"interrogative", direct:`She said, “Whose pen is this?”`, indirect:`She asked whose pen that was.`},
{id:44, topic:"interrogative", direct:`The stranger said, “What is your name?”`, indirect:`The stranger asked what my name was.`},
{id:45, topic:"interrogative", direct:`The coach said, “How long have you practised?”`, indirect:`The coach asked how long I had practised.`},
{id:46, topic:"interrogative", direct:`Mother said, “Where did you keep the keys?”`, indirect:`Mother asked where I had kept the keys.`},
{id:47, topic:"interrogative", direct:`He said to her, “Why do you look sad?”`, indirect:`He asked her why she looked sad.`},
{id:48, topic:"interrogative", direct:`The teacher said, “What is the capital of India?”`, indirect:`The teacher asked what the capital of India is.`},
{id:49, topic:"interrogative", direct:`She said, “How many students are absent today?”`, indirect:`She asked how many students were absent that day.`},
{id:50, topic:"interrogative", direct:`He said to me, “When did you arrive here?”`, indirect:`He asked me when I had arrived there.`},
];
