const BANK = [
  {id:1, topic:"assertive", direct:`She said, “I like tea.”`, indirect:`She said that she liked tea.`},
  {id:2, topic:"assertive", direct:`He said, “I am writing a letter.”`, indirect:`He said that he was writing a letter.`},
  {id:3, topic:"assertive", direct:`They said, “We have won the match.”`, indirect:`They said that they had won the match.`},
  {id:4, topic:"timeplace", direct:`Ramesh said, “I bought a new book yesterday.”`, indirect:`Ramesh said that he had bought a new book the previous day.`},
  {id:5, topic:"assertive", direct:`The old man said, “I was feeling weak.”`, indirect:`The old man said that he had been feeling weak.`},
  {id:6, topic:"modals", direct:`The doctor said, “You must take this medicine.”`, indirect:`The doctor said that I must take that medicine.`},
  {id:7, topic:"assertive", direct:`Mina said to me, “I have completed the work.”`, indirect:`Mina told me that she had completed the work.`},
  {id:8, topic:"timeplace", direct:`The boys said, “We are playing in the field now.”`, indirect:`The boys said that they were playing in the field then.`},
  {id:9, topic:"modals", direct:`Father said, “I will return tomorrow.”`, indirect:`Father said that he would return the next day.`},
  {id:10, topic:"assertive", direct:`The teacher said, “Honesty is the best policy.”`, indirect:`The teacher said that honesty is the best policy.`},
  {id:11, topic:"assertive", direct:`She said, “I have been reading for two hours.”`, indirect:`She said that she had been reading for two hours.`},
  {id:12, topic:"modals", direct:`He said, “I cannot attend the meeting.”`, indirect:`He said that he could not attend the meeting.`},
  {id:13, topic:"assertive", direct:`Rahul said to his friend, “I have lost my pen.”`, indirect:`Rahul told his friend that he had lost his pen.`},
  {id:14, topic:"assertive", direct:`The guard said, “The gate closes at 9 p.m.”`, indirect:`The guard said that the gate closed at 9 p.m.`},
  {id:15, topic:"assertive", direct:`The child said, “I was sleeping.”`, indirect:`The child said that he/she had been sleeping.`},
  {id:16, topic:"assertive", direct:`The woman said, “I have never seen such a place.”`, indirect:`The woman said that she had never seen such a place.`},
  {id:17, topic:"modals", direct:`He said, “We will start next week.”`, indirect:`He said that they would start the following week.`},
  {id:18, topic:"assertive", direct:`The shopkeeper said, “These mangoes are fresh.”`, indirect:`The shopkeeper said that those mangoes were fresh.`},
  {id:19, topic:"modals", direct:`She said, “I may go there.”`, indirect:`She said that she might go there.`},
  {id:20, topic:"assertive", direct:`The farmer said, “It rained heavily last night.”`, indirect:`The farmer said that it had rained heavily the previous night.`},
  {id:21, topic:"assertive", direct:`The students said, “We are preparing for the test.”`, indirect:`The students said that they were preparing for the test.`},
  {id:22, topic:"assertive", direct:`She said to her mother, “I have done my duty.”`, indirect:`She told her mother that she had done her duty.`},
  {id:23, topic:"assertive", direct:`He said, “I had a headache.”`, indirect:`He said that he had had a headache.`},
  {id:24, topic:"assertive", direct:`The coach said, “Practice makes a player perfect.”`, indirect:`The coach said that practice makes a player perfect.`},
  {id:25, topic:"modals", direct:`He said, “I shall help you.”`, indirect:`He said that he would help me.`},
  {id:26, topic:"interrogative", direct:`He said to me, “Are you coming today?”`, indirect:`He asked me if I was coming that day.`},
  {id:27, topic:"interrogative", direct:`She said, “Do you know the answer?”`, indirect:`She asked if I knew the answer.`},
  {id:28, topic:"interrogative", direct:`They said to him, “Have you seen this film?”`, indirect:`They asked him whether he had seen that film.`},
  {id:29, topic:"interrogative", direct:`The teacher said to the student, “Did you complete the lesson?”`, indirect:`The teacher asked the student if he/she had completed the lesson.`},
  {id:30, topic:"modals", direct:`Mother said to me, “Will you help me?”`, indirect:`Mother asked me if I would help her.`},
  {id:31, topic:"modals", direct:`He said, “Can you swim?”`, indirect:`He asked if I could swim.`},
  {id:32, topic:"modals", direct:`She said, “May I come in?”`, indirect:`She asked if she might come in.`},
  {id:33, topic:"interrogative", direct:`The man said to the boy, “Is your father at home?”`, indirect:`The man asked the boy if his father was at home.`},
  {id:34, topic:"interrogative", direct:`The doctor said to her, “Do you smoke?”`, indirect:`The doctor asked her if she smoked.`},
  {id:35, topic:"interrogative", direct:`The officer said, “Have the workers arrived?”`, indirect:`The officer asked if the workers had arrived.`},
  {id:36, topic:"interrogative", direct:`He said to me, “Where are you going?”`, indirect:`He asked me where I was going.`},
  {id:37, topic:"interrogative", direct:`She said, “What are you doing now?”`, indirect:`She asked what I was doing then.`},
  {id:38, topic:"interrogative", direct:`Father said, “Why were you late yesterday?”`, indirect:`Father asked why I had been late the previous day.`},
  {id:39, topic:"interrogative", direct:`The teacher said, “How did you solve the problem?”`, indirect:`The teacher asked how I had solved the problem.`},
  {id:40, topic:"modals", direct:`She said to him, “When will you meet me?”`, indirect:`She asked him when he would meet her.`},
  {id:41, topic:"interrogative", direct:`The boy said, “Who is calling me?”`, indirect:`The boy asked who was calling him.`},
  {id:42, topic:"interrogative", direct:`He said, “Which book do you want?”`, indirect:`He asked which book I wanted.`},
  {id:43, topic:"interrogative", direct:`She said, “Whose pen is this?”`, indirect:`She asked whose pen that was.`},
  {id:44, topic:"interrogative", direct:`The stranger said, “What is your name?”`, indirect:`The stranger asked what my name was.`},
  {id:45, topic:"interrogative", direct:`The coach said, “How long have you practised?”`, indirect:`The coach asked how long I had practised.`},
  {id:46, topic:"interrogative", direct:`Mother said, “Where did you keep the keys?”`, indirect:`Mother asked where I had kept the keys.`},
  {id:47, topic:"interrogative", direct:`He said to her, “Why do you look sad?”`, indirect:`He asked her why she looked sad.`},
  {id:48, topic:"interrogative", direct:`The teacher said, “What is the capital of India?”`, indirect:`The teacher asked what the capital of India is.`},
  {id:49, topic:"interrogative", direct:`She said, “How many students are absent today?”`, indirect:`She asked how many students were absent that day.`},
  {id:50, topic:"interrogative", direct:`He said to me, “When did you arrive here?”`, indirect:`He asked me when I had arrived there.`},
  {id:51, topic:"imperative", direct:`The teacher said, “Open your books.”`, indirect:`The teacher ordered the students to open their books.`},
  {id:52, topic:"imperative", direct:`Mother said to me, “Do not waste time.”`, indirect:`Mother advised me not to waste time.`},
  {id:53, topic:"imperative", direct:`He said to her, “Please help me.”`, indirect:`He requested her to help him.`},
  {id:54, topic:"imperative", direct:`The officer said, “Stand up.”`, indirect:`The officer ordered them to stand up.`},
  {id:55, topic:"imperative", direct:`Father said, “Do not tell a lie.”`, indirect:`Father forbade me to tell a lie.`},
  {id:56, topic:"imperative", direct:`She said to the boy, “Go home at once.”`, indirect:`She ordered the boy to go home at once.`},
  {id:57, topic:"imperative", direct:`The doctor said, “Take rest for a week.”`, indirect:`The doctor advised me to take rest for a week.`},
  {id:58, topic:"imperative", direct:`He said, “Let us go for a walk.”`, indirect:`He suggested that we should go for a walk.`},
  {id:59, topic:"imperative", direct:`The teacher said, “Let the boy come in.”`, indirect:`The teacher ordered that the boy should be allowed to come in.`},
  {id:60, topic:"imperative", direct:`She said, “Please do not make a noise.”`, indirect:`She requested them not to make a noise.`},
  {id:61, topic:"optative", direct:`He said, “May you live long.”`, indirect:`He wished that I might live long.`},
  {id:62, topic:"optative", direct:`She said, “May God bless you.”`, indirect:`She prayed that God might bless me.`},
  {id:63, topic:"optative", direct:`He said, “Would that I were a king!”`, indirect:`He wished that he were a king.`},
  {id:64, topic:"optative", direct:`She said, “What a beautiful scene it is!”`, indirect:`She exclaimed with joy that it was a very beautiful scene.`},
  {id:65, topic:"optative", direct:`He said, “Alas! I am undone.”`, indirect:`He exclaimed with sorrow that he was undone.`},
  {id:66, topic:"optative", direct:`She said, “Hurrah! We have won.”`, indirect:`She exclaimed with joy that they had won.`},
  {id:67, topic:"optative", direct:`He said, “How clever you are!”`, indirect:`He exclaimed that I was very clever.`},
  {id:68, topic:"optative", direct:`She said, “What a fool I am!”`, indirect:`She exclaimed with regret that she was a great fool.`},
  {id:69, topic:"timeplace", direct:`He said, “I saw him here yesterday.”`, indirect:`He said that he had seen him there the previous day.`},
  {id:70, topic:"timeplace", direct:`She said, “I shall come tomorrow.”`, indirect:`She said that she would come the next day.`},
  {id:71, topic:"timeplace", direct:`He said, “I am busy now.”`, indirect:`He said that he was busy then.`},
  {id:72, topic:"timeplace", direct:`She said, “I met him today.”`, indirect:`She said that she had met him that day.`},
  {id:73, topic:"assertive", direct:`He said, “The sun rises in the east.”`, indirect:`He said that the sun rises in the east.`},
  {id:74, topic:"assertive", direct:`She said, “I know him.”`, indirect:`She said that she knew him.`},
  {id:75, topic:"assertive", direct:`They said, “We are going to school.”`, indirect:`They said that they were going to school.`},
  {id:76, topic:"assertive", direct:`He said to me, “You are wrong.”`, indirect:`He told me that I was wrong.`},
  {id:77, topic:"assertive", direct:`She said, “I have finished the work.”`, indirect:`She said that she had finished the work.`},
  {id:78, topic:"assertive", direct:`He said, “I was reading a novel.”`, indirect:`He said that he had been reading a novel.`},
  {id:79, topic:"assertive", direct:`She said, “I will help you.”`, indirect:`She said that she would help me.`},
  {id:80, topic:"modals", direct:`He said, “You must work hard.”`, indirect:`He said that I must work hard.`},
  {id:81, topic:"modals", direct:`She said, “I can speak English.”`, indirect:`She said that she could speak English.`},
  {id:82, topic:"modals", direct:`He said, “May I leave the room?”`, indirect:`He asked if he might leave the room.`},
  {id:83, topic:"interrogative", direct:`She said, “Is he coming?”`, indirect:`She asked if he was coming.`},
  {id:84, topic:"interrogative", direct:`He said, “Have you done it?”`, indirect:`He asked if I had done it.`},
  {id:85, topic:"interrogative", direct:`She said, “Where does he live?”`, indirect:`She asked where he lived.`},
  {id:86, topic:"interrogative", direct:`He said, “Why are you crying?”`, indirect:`He asked why I was crying.`},
  {id:87, topic:"imperative", direct:`She said, “Sit down.”`, indirect:`She ordered me to sit down.`},
  {id:88, topic:"imperative", direct:`He said, “Do not go there.”`, indirect:`He forbade me to go there.`},
  {id:89, topic:"imperative", direct:`She said, “Please wait.”`, indirect:`She requested me to wait.`},
  {id:90, topic:"optative", direct:`He said, “May you succeed.”`, indirect:`He wished that I might succeed.`},
  {id:91, topic:"assertive", direct:`The teacher said, “The earth moves round the sun.”`, indirect:`The teacher said that the earth moves round the sun.`},
  {id:92, topic:"assertive", direct:`He said, “I have been living here for five years.”`, indirect:`He said that he had been living there for five years.`},
  {id:93, topic:"assertive", direct:`She said to me, “I shall give you a book.”`, indirect:`She told me that she would give me a book.`},
  {id:94, topic:"interrogative", direct:`He said, “What is your father?”`, indirect:`He asked what my father was.`},
  {id:95, topic:"interrogative", direct:`She said, “How old are you?”`, indirect:`She asked how old I was.`},
  {id:96, topic:"imperative", direct:`The captain said, “March on.”`, indirect:`The captain ordered the soldiers to march on.`},
  {id:97, topic:"optative", direct:`He said, “What a pity!”`, indirect:`He exclaimed that it was a great pity.`},
  {id:98, topic:"timeplace", direct:`She said, “I shall go there tomorrow.”`, indirect:`She said that she would go there the next day.`},
  {id:99, topic:"assertive", direct:`He said, “I bought this pen yesterday.”`, indirect:`He said that he had bought that pen the previous day.`},
  {id:100, topic:"modals", direct:`She said, “I must leave now.”`, indirect:`She said that she had to leave then.`},
  {id:101, topic:"assertive", direct:`The boy said, “I am hungry.”`, indirect:`The boy said that he was hungry.`},
  {id:102, topic:"assertive", direct:`She said, “We play cricket every day.”`, indirect:`She said that they played cricket every day.`},
  {id:103, topic:"interrogative", direct:`He said to her, “Are you happy?”`, indirect:`He asked her if she was happy.`},
  {id:104, topic:"interrogative", direct:`She said, “Who broke the glass?”`, indirect:`She asked who had broken the glass.`},
  {id:105, topic:"imperative", direct:`Mother said, “Wash your hands.”`, indirect:`Mother told me to wash my hands.`},
  {id:106, topic:"imperative", direct:`He said, “Let us start the work.”`, indirect:`He suggested that we should start the work.`},
  {id:107, topic:"optative", direct:`She said, “May you be happy.”`, indirect:`She wished that I might be happy.`},
  {id:108, topic:"optative", direct:`He said, “Alas! He is dead.”`, indirect:`He exclaimed with sorrow that he was dead.`},
  {id:109, topic:"timeplace", direct:`She said, “I saw him this morning.”`, indirect:`She said that she had seen him that morning.`},
  {id:110, topic:"assertive", direct:`He said, “I wrote a letter.”`, indirect:`He said that he had written a letter.`},
  {id:111, topic:"assertive", direct:`She said, “I am learning French.”`, indirect:`She said that she was learning French.`},
  {id:112, topic:"modals", direct:`He said, “You should obey your parents.”`, indirect:`He said that I should obey my parents.`},
  {id:113, topic:"interrogative", direct:`She said, “Did you see the film?”`, indirect:`She asked if I had seen the film.`},
  {id:114, topic:"interrogative", direct:`He said, “When will the train arrive?”`, indirect:`He asked when the train would arrive.`},
  {id:115, topic:"imperative", direct:`The teacher said, “Do not talk in the class.”`, indirect:`The teacher forbade the students to talk in the class.`},
  {id:116, topic:"optative", direct:`She said, “What a lovely flower!”`, indirect:`She exclaimed with joy that it was a very lovely flower.`},
  {id:117, topic:"assertive", direct:`He said, “I know the way.”`, indirect:`He said that he knew the way.`},
  {id:118, topic:"assertive", direct:`She said to him, “I like you.”`, indirect:`She told him that she liked him.`},
  {id:119, topic:"timeplace", direct:`He said, “I shall return next week.”`, indirect:`He said that he would return the following week.`},
  {id:120, topic:"modals", direct:`She said, “I may come tomorrow.”`, indirect:`She said that she might come the next day.`},
  {id:121, topic:"interrogative", direct:`He said, “Can you help me?”`, indirect:`He asked if I could help him.`},
  {id:122, topic:"interrogative", direct:`She said, “Why did you come late?”`, indirect:`She asked why I had come late.`},
  {id:123, topic:"imperative", direct:`Father said, “Bring me a glass of water.”`, indirect:`Father ordered me to bring him a glass of water.`},
  {id:124, topic:"optative", direct:`He said, “May peace prevail.”`, indirect:`He prayed that peace might prevail.`},
  {id:125, topic:"assertive", direct:`She said, “I have lost my keys.”`, indirect:`She said that she had lost her keys.`},
  {id:126, topic:"assertive", direct:`He said, “We shall overcome.”`, indirect:`He said that they would overcome.`},
  {id:127, topic:"timeplace", direct:`She said, “I was here last night.”`, indirect:`She said that she had been there the previous night.`},
  {id:128, topic:"modals", direct:`He said, “You ought to respect elders.”`, indirect:`He said that I ought to respect elders.`},
  {id:129, topic:"interrogative", direct:`She said, “How are you?”`, indirect:`She asked how I was.`},
  {id:130, topic:"interrogative", direct:`He said, “What do you want?”`, indirect:`He asked what I wanted.`},
  {id:131, topic:"imperative", direct:`The nurse said, “Take this medicine.”`, indirect:`The nurse advised me to take that medicine.`},
  {id:132, topic:"optative", direct:`She said, “Hurrah! My brother has come.”`, indirect:`She exclaimed with joy that her brother had come.`},
  {id:133, topic:"assertive", direct:`He said, “I am not feeling well.”`, indirect:`He said that he was not feeling well.`},
  {id:134, topic:"assertive", direct:`She said, “The train left an hour ago.”`, indirect:`She said that the train had left an hour before.`},
  {id:135, topic:"timeplace", direct:`He said, “I shall see you the day after tomorrow.”`, indirect:`He said that he would see me in two days.`},
  {id:136, topic:"modals", direct:`She said, “I will never forget you.”`, indirect:`She said that she would never forget me.`},
  {id:137, topic:"interrogative", direct:`He said, “Is the door open?”`, indirect:`He asked if the door was open.`},
  {id:138, topic:"interrogative", direct:`She said, “Where have you been?”`, indirect:`She asked where I had been.`},
  {id:139, topic:"imperative", direct:`The guide said, “Follow me.”`, indirect:`The guide ordered us to follow him.`},
  {id:140, topic:"optative", direct:`He said, “What a mess this is!”`, indirect:`He exclaimed with surprise that that was a mess.`},
  {id:141, topic:"assertive", direct:`She said, “I never tell a lie.”`, indirect:`She said that she never told a lie.`},
  {id:142, topic:"assertive", direct:`He said to me, “You will succeed.”`, indirect:`He told me that I would succeed.`},
  {id:143, topic:"optative", direct:`She said, “What a mess this is!”`, indirect:`She exclaimed with surprise that that was a mess.`},
  {id:144, topic:"optative", direct:`He said, “May you be blessed!”`, indirect:`He wished that I/he/she might be blessed.`}
];
